name: CI

on:
  create:
    branches:
    - release/**
    - hotfix/**
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop
    - feature/**
    - hotfix/**
    
jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'src\Our.Umbraco.SearchSpellCheck.sln'

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x
        
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      
    - name: NuGet Restore
      run: nuget restore $env:SOLUTION

    - name: Build
      run: dotnet build $env:SOLUTION --configuration=$env:BUILD_CONFIG --no-restore
          
    - name: Add GitHub Package Source
      if: startsWith(github.ref, 'refs/heads/release')
      run: dotnet nuget add source --username rickbutterfield --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/rickbutterfield/index.json"
      
    - name: Publish to GitHub
      if: startsWith(github.ref, 'refs/heads/release')
      run: nuget push **\*.nupkg -Source "github" --api-key ${{ secrets.PAT }}
      
    - name: Publish to NuGet
      if: startsWith(github.ref, 'refs/heads/release')
      run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
